-- Actualizar la tabla de productos
ALTER TABLE productos
ADD COLUMN IF NOT EXISTS descripcion_detallada TEXT,
ADD COLUMN IF NOT EXISTS modelo VARCHAR(100),
ADD COLUMN IF NOT EXISTS marca VARCHAR(100),
ADD COLUMN IF NOT EXISTS referencia VARCHAR(100),
ADD COLUMN IF NOT EXISTS costo_anterior DECIMAL(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS costo_actual DECIMAL(12,2) DEFAULT 0,
DROP COLUMN IF EXISTS costo_promedio,
DROP COLUMN IF EXISTS redondeo; 